
<div>
    
<p style="margin:0 0 20px;">In order to start age verifying your customers you will need to create a new Magento Integration and register with <?php echo $block->getUnityName(); ?>. You can do so by clicking on the button below:</p>

<?php //echo __('Hello WOrld'); ?>
<button id="save" title="Save Config" onclick="window.open('<?php echo $block->getUrl('avregister/register'); ?>','_blank')" type="button" class="action-default scalable save primary ui-button ui-corner-all ui-widget">
    <span>Click here to register</span>
</button>

<span style="margin-left:20px;color:#206eba;cursor:pointer" class=" ac-api-user" target="_blank" href="" onclick="window.open('<?php echo $block->getUrl('avregister/register'); ?>','_blank')">Try me first</span>
</div>
<!--p style="margin-top:20px;color:#999;font-style:italic;">This integration is provided in partnership with Verifico</p-->