<?php
// echo 'hello';
// print_r($block->getRegisterData());

$data = $block->getRegisterData();
?>
<div style="margin:30px 40px;"><h1>Redirecting, please wait...</h1></div>
<style>.menu-wrapper {display:none !important;}</style>
<script>
    require([
        'jquery'
    ],function($) {
         $(document).ready(function() {

            // jquery extend function
            $.extend(
                {
                    redirectPost: function(location, args)
                    {
                        var form = '';
                        $.each( args, function( key, value ) {
                            value = value.split('"').join('\"')
                            form += '<input type="hidden" name="'+key+'" value="'+value+'">';
                        });
                        $('<form action="' + location + '" method="POST">' + form + '</form>').appendTo($(document.body)).submit();
                    }
                });

           

               
                    
                        var redirect = '<?php echo $block->getUnityRegisterUrl() ?>';
                        $.redirectPost(redirect, {
                            'name': "<?= $data['name'] ?>", 
                            'url': "<?= $data['url'] ?>", 
                            'email': "<?= $data['email'] ?>", 
                            'logo': "<?= $data['logo'] ?>",
                            'platform': 'magento'
                        });
                    
                    
                
            

                

               
         });  
     });
</script>